version: '3.7'
services:
  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresdb:
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  node:
    image: node:8
    ports:
      - '9999:9999'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./gate-simulator:/home/node/app
    command: npm start

